#!/usr/bin/php
<?php
//Modifier les variables suivantes
$Hostname='XXX.XXX.XXX.XXX';
$Username='XXX';
$Password='XXX'; 
$Command='XXXXX' ;
  
$ssh = ssh2_connect($Hostname, 22);
ssh2_auth_password($ssh, $Username, $Password);
$stream = ssh2_exec($ssh, $Command);
stream_set_blocking($stream, true);

//renvoi la sortie de la commande si besoin
$response = '';
while($buffer = fread($stream, 4096)) {
$response .= $buffer;
}
 
fclose($stream);
echo $response;
?>
